# Generated by Django 3.1.5 on 2021-01-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
