# Generated by Django 3.1.5 on 2021-01-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_bot', '0002_auto_20210125_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='close_price',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='candle',
            name='hight_price',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='candle',
            name='low_price',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='candle',
            name='open_price',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
